### ISSUE TITLE
“opencc 初始化失败！项目将没有繁简转化功能 No module named 'opencc'”

### ISSUE THREAD

**Issue by chflame163** [liwenju0/cutword#14]
Windows11 下，执行到import cutword时出现此消息。

**Comment by liwenju0** [comment]
这个不影响使用。这个分词工具不支持繁体的分词，所以，对于繁体句子，会尝试转化成简体。使用的包是opencc。
如果opencc没有安装，会提示该报警。
对于使用简体中文的情况，可以忽略该报警。

**Comment by chflame163** [comment]
> 这个不影响使用。这个分词工具不支持繁体的分词，所以，对于繁体句子，会尝试转化成简体。使用的包是opencc。 如果opencc没有安装，会提示该报警。 对于使用简体中文的情况，可以忽略该报警。

能否屏蔽？我在开发一个ComfyUI 插件[ComfyUI Word Cloud](https://github.com/chflame163/ComfyUI_WordCloud)，这个项目当前使用jieba分词，想尝试使用cutword，但是我不希望输出无关的消息。
