### ISSUE TITLE
Can I convert a long Chinese text without punctuation into a bunch of sentences? How can I use  cutword to implement it ？  我可以将一个无标点的中文长文本转换为一堆句子吗，请问我该如何利用cutword实现

### ISSUE THREAD

**Issue by hellostronger** [liwenju0/cutword#16]
Can I convert a long Chinese text without punctuation into a bunch of sentences? How can I use  cutword to implement it ？  我可以将一个无标点的中文长文本转换为一堆句子吗，请问我该如何利用cutword实现

**Comment by liwenju0** [comment]
不支持的。
