### ISSUE TITLE
能提取电话或者邮件吗

### ISSUE THREAD

**Issue by Tendo33** [liwenju0/cutword#19]

**Comment by liwenju0** [comment]
可以的

**Comment by Tendo33** [comment]
但我看命名实体识别里面的分类就全归到基础里了，能加字段吗

**Comment by liwenju0** [comment]
是归到基础里面了，暂时加不了字段

**Comment by Tendo33** [comment]
那如果我只想删除文章中的邮件和电话，有什么好的办法吗

**Comment by xinlingqudongX** [comment]
> 那如果我只想删除文章中的邮件和电话，有什么好的办法吗

这些用正则就可以匹配，直接正则抹掉

**Comment by Tendo33** [comment]
> > 那如果我只想删除文章中的邮件和电话，有什么好的办法吗
> 
> 这些用正则就可以匹配，直接正则抹掉

正则的话，要写的pattern比较多，数据也比较复杂，不能全过滤全

**Comment by xinlingqudongX** [comment]
> > > 那如果我只想删除文章中的邮件和电话，有什么好的办法吗
> > 
> > 
> > 这些用正则就可以匹配，直接正则抹掉
> 
> 正则的话，要写的pattern比较多，数据也比较复杂，不能全过滤全

不对吧，邮件和电话是有固定格式的，如果说你的邮件和电话不符合格式的话，即便是用其他的分词工具也是无法提取的

**Comment by liwenju0** [comment]
可以在base的基础上做简单的规则过滤，比如电话，可以根据长度，前三个数字来确定，如限定为139、136等，邮件也可以用类似的方法
