### ISSUE TITLE
可否减少cutword中对torch的重量库的全局依赖

### ISSUE THREAD

**Issue by imClumsyPanda** [liwenju0/cutword#22]
非常感谢开源cutword项目！目前在使用过程中遇到，仅需使用cutter进行分词时，也因为__init__中有from .ner import NER 的代码，导致因为NER中默认全局需要import torch，所以必须先安装torch才能使用Cutter.cutword的情况，期望在后续版本中能够对这一问题进行改善，在需要使用到torch的ner场景中，再让torch成为必须的库。

**Comment by liwenju0** [comment]
好的，感谢建议

**Comment by liwenju0** [comment]
已升级0.1.1，在没有torch时，仍然可以使用分词功能

**Comment by imClumsyPanda** [comment]
非常感谢！
